### ISSUE TITLE
Unknown function: getbufinfo

### ISSUE THREAD

**Issue by tuyy** [apalmer1377/factorus#10]
When I try to do any rename I get this error:

```
Error detected while processing function factorus#command:
line    3:
E117: Unknown function: getbufinfo
E116: Invalid arguments for function map(getbufinfo(),{n,val -> val['name']})
E15: Invalid expression: map(getbufinfo(),{n,val -> val['name']})
Error detected while processing function factorus#command..<SNR>102_handleError:
line    3:
E117: Unknown function: getbufinfo
E15: Invalid expression: getbufinfo()
```

How can we solve this?

**Comment by apalmer1377** [comment]
I haven't been able to replicate this. What language are you refactoring with, and what Vim runtime are you using?

**Comment by apalmer1377** [comment]
It looks like you might have a very old version of Vim, that doesn't have the getbufinfo() command. The command has been part of Vim since 2017, so updating to the newest version should fix the issue.

**Comment by apalmer1377** [comment]
I added a check to make sure the Vim installation has the proper patch, so I'm closing this for now. If the issue persists with up-to-date versions of Vim, I'll re-open it.
