### ISSUE TITLE
FExtractMethod contains error - illegal variable name a:closes

### ISSUE THREAD

**Issue by asaf-erlich** [apalmer1377/factorus#5]
Just installed this for the first time. Used it for a day and tried FExtractMethod in a python file after visually selecting a block of text and saw the following error:

>An unexpected error has occurred: Vim(let):E461: Illegal variable name: a:closes, at function factorus#command[30]..python#factorus#extractMethod[7]..<SNR>100_manualEx
tract[21]..<SNR>100_getAllRelevantLines, line 5

I tried again without visual select and I obtained the same error. Let me know if you need more info.

Thank you,
-Asaf

**Comment by asaf-erlich** [comment]
Looked through the code, the line where it's complaining is right here: https://github.com/apalmer1377/factorus/blob/768595fe87e16a2cca95dd3193c3ed613512f033/autoload/python/factorus.vim#L592

**Comment by apalmer1377** [comment]
Thanks for letting me know! I thought I had fixed this a couple days ago, but it looks like there were a couple lines that I missed. I just pushed a fix that changes the variable to a local one, so let me know if it persists.

**Comment by asaf-erlich** [comment]
@apalmer1377 thanks for the quick fix! I'll update it and report back shortly.

**Comment by asaf-erlich** [comment]
So if I run it without selecting lines it throws this error:

>An unexpected error has occurred: Vim(let):E684: list index out of range: 2, at function factorus#command[30]..python#factorus#extractMethod[62]..<SNR>106_wrapDecs, line 25

If I run it selecting the lines I want to extract a method from it doesn't grab all of them. Basically I have code that looks like this:
```
if word == 'something':
    variable = os.environ.get('something')
else:
    other_variable = os.environ.get(word)
```

If I select the whole if and else it only extracts the if part leaving behind the stuff in the if and the else which leaves the code in a state that won't run. It looks something like this afterwards:
```
word = newFactorusMethod(word)
    variable = os.environ.get('something')
else:
    other_variable = os.environ.get(word)

def newFactorusMethod(environment_variable_name):
                                               if word == 'something':
                                               return word
```

**Comment by apalmer1377** [comment]
Yeah, it looks like python method extraction requires a complete overhaul; if I remember correctly, I didn't test it on a huge sample of functions, so I must have missed a large amount of cases that cause it to break. I'll be working on it over this week, but for now I think it's safe to say that python method extraction is not functional.

**Comment by apalmer1377** [comment]
I just pushed some significant changes to the branch 5-python-extract-method; ran some tests on some sample methods and a couple of methods in the sympy repository, and it seems to be working better. If you find it works now, I can merge the changes into the master branch.

**Comment by apalmer1377** [comment]
I'm assuming this issue has been fixed by the changes to the other branch, so I merged the branch into master and am closing this issue.
