### ISSUE TITLE
E128: Function name must start with a capital

### ISSUE THREAD

**Issue by lwojaczek** [apalmer1377/factorus#7]
When I try to do any rename I get this error:
`An unexpected error has occurred: Vim(function):E128: Function name must start with a capital or "s:": s;manualExtract(args), at /home/wojak/.vim/plugged/factorus/autoload/cpp/factorus.vim, line 2355`
I am using vim 8.1.

**Comment by apalmer1377** [comment]
It looks like there was a typo in the file, a mistaken semicolon instead of a colon. I just pushed a fix, and it should work fine now.

**Comment by lwojaczek** [comment]
Now I get:
`Factorus:Vim(if):E132: Function call depth is higher than 'maxfuncdepth', at function <SNR>38_ActivateBuffer[2]..<SNR>38_UpdateTabBufData, line 14`

**Comment by apalmer1377** [comment]
In your project, do you have two different files with the same name, but in different directories, with one file including the other file using "#include"?

**Comment by lwojaczek** [comment]
Nope, all files have unique names. Only directories share names:
> find src test include -printf "%f\n" | sort | uniq -c
>       1 CMakeLists.txt
>       1 CMakeLists.txt.in
>       1 Command.cpp
>       1 Command.h
>       3 commands
>       1 ConsoleInput.cpp
>       1 ConsoleInput.h
>       1 ConsoleInputTest.cpp
>       1 ConsoleOutput.cpp
>       1 ConsoleOutput.h
>       1 ConsoleOutputTest.cpp
>       3 core
>       1 Game.cpp
>       1 Game.h
>       1 GameTest.cpp
>       1 Help.cpp
>       1 Help.h
>       1 HelpTest.cpp
>       1 include
>       1 Input.h
>       1 main.cpp
>       1 MainMenu.cpp
>       1 MainMenu.h
>       1 MainMenuTest.cpp
>       1 MockInput.h
>       1 MockOutput.h
>       1 Output.h
>       1 ParamCommand.h
>       1 ParamCommandTest.cpp
>       1 SimpleCommand.h
>       1 SimpleCommandTest.cpp
>       1 src
>       1 State.cpp
>       1 State.h
>       3 states
>       1 StateTest.cpp
>       1 test

**Comment by apalmer1377** [comment]
Interesting... are there any files that include each other, then, or a file that includes itself? The issue is that the code is recursing on the same files infinitely, so I'm trying to figure out exactly what might have caused the recursion.

**Comment by lwojaczek** [comment]
I can't seen any include recursion. Code compiles without any problem.

**Comment by apalmer1377** [comment]
Okay, I think the issue has something to do with the algorithm performing too many recursive calls; I pushed a fix that gets rid of the recursion, so it should work better and faster now. I'll keep the issue open in case it isn't fixed.

**Comment by lwojaczek** [comment]
Now it is working, thanks!
